-- MySQL Script generated by MySQL Workbench
-- Tue Nov 18 00:08:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotel_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel_project` DEFAULT CHARACTER SET utf8 ;
USE `hotel_project` ;

-- -----------------------------------------------------
-- Table `hotel_project`.`Room_Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_project`.`Room_Types` (
  `type_id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_project`.`Rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_project`.`Rooms` (
  `room_number` INT NOT NULL,
  `floor` INT NULL,
  `status` VARCHAR(20) NULL,
  `type_id` INT NOT NULL,
  PRIMARY KEY (`room_number`),
  INDEX `fk_Rooms_Room_Types_idx` (`type_id` ASC) VISIBLE,
  CONSTRAINT `fk_Rooms_Room_Types`
    FOREIGN KEY (`type_id`)
    REFERENCES `hotel_project`.`Room_Types` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_project`.`Membership_Tiers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_project`.`Membership_Tiers` (
  `tier_id` INT NOT NULL AUTO_INCREMENT,
  `tier_name` VARCHAR(45) NULL,
  `stay_requirement` INT NULL,
  `discount_rate` DECIMAL(3,2) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`tier_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_project`.`Guests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_project`.`Guests` (
  `guest_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `password` VARCHAR(255) NULL,
  `tier_id` INT NOT NULL,
  PRIMARY KEY (`guest_id`),
  INDEX `fk_Guests_Membership_Tiers1_idx` (`tier_id` ASC) VISIBLE,
  CONSTRAINT `fk_Guests_Membership_Tiers1`
    FOREIGN KEY (`tier_id`)
    REFERENCES `hotel_project`.`Membership_Tiers` (`tier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_project`.`Reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_project`.`Reservations` (
  `reservation_id` INT NOT NULL AUTO_INCREMENT,
  `check_in_date` DATE NOT NULL,
  `check_out_date` DATE NOT NULL,
  `total_price` DECIMAL(10,2) NULL,
  `status` VARCHAR(20) NULL,
  `guest_id` INT NOT NULL,
  `room_number` INT NOT NULL,
  PRIMARY KEY (`reservation_id`),
  INDEX `fk_Reservations_Guests1_idx` (`guest_id` ASC) VISIBLE,
  INDEX `fk_Reservations_Rooms1_idx` (`room_number` ASC) VISIBLE,
  CONSTRAINT `fk_Reservations_Guests1`
    FOREIGN KEY (`guest_id`)
    REFERENCES `hotel_project`.`Guests` (`guest_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservations_Rooms1`
    FOREIGN KEY (`room_number`)
    REFERENCES `hotel_project`.`Rooms` (`room_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_project`.`Amenities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_project`.`Amenities` (
  `amenity_id` INT NOT NULL AUTO_INCREMENT,
  `amenity_name` VARCHAR(45) NOT NULL,
  `daily_capacity` INT NULL,
  `is_free` TINYINT(1) NULL,
  PRIMARY KEY (`amenity_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_project`.`Service_Usage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_project`.`Service_Usage` (
  `usage_id` INT NOT NULL AUTO_INCREMENT,
  `usage_date` DATETIME NULL,
  `quantity` INT NULL,
  `reservation_id` INT NOT NULL,
  `amenity_id` INT NOT NULL,
  PRIMARY KEY (`usage_id`),
  INDEX `fk_Service_Usage_Reservations1_idx` (`reservation_id` ASC) VISIBLE,
  INDEX `fk_Service_Usage_Amenities1_idx` (`amenity_id` ASC) VISIBLE,
  CONSTRAINT `fk_Service_Usage_Reservations1`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `hotel_project`.`Reservations` (`reservation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_Usage_Amenities1`
    FOREIGN KEY (`amenity_id`)
    REFERENCES `hotel_project`.`Amenities` (`amenity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_project`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_project`.`Employees` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `role` VARCHAR(20) NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_project`.`Tier_Benefits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_project`.`Tier_Benefits` (
  `benefit_id` INT NOT NULL AUTO_INCREMENT,
  `access_level` INT NULL,
  `tier_id` INT NOT NULL,
  `amenity_id` INT NOT NULL,
  PRIMARY KEY (`benefit_id`),
  INDEX `fk_Tier_Benefits_Membership_Tiers1_idx` (`tier_id` ASC) VISIBLE,
  INDEX `fk_Tier_Benefits_Amenities1_idx` (`amenity_id` ASC) VISIBLE,
  CONSTRAINT `fk_Tier_Benefits_Membership_Tiers1`
    FOREIGN KEY (`tier_id`)
    REFERENCES `hotel_project`.`Membership_Tiers` (`tier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tier_Benefits_Amenities1`
    FOREIGN KEY (`amenity_id`)
    REFERENCES `hotel_project`.`Amenities` (`amenity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
